// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgcqsfvtnrgegmqvkhtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnY3FzZnZ0bnJnZWdtcXZraHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjUzNDQsImV4cCI6MjA2NDIwMTM0NH0.nyzsbMVcTP53ozRsBzRGltzRRxYt-0wwoXM_d7wx7yE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);